### ISSUE TITLE
that one character isnt even on my keyboard

### ISSUE THREAD

**Issue by Hezuikn** [adam-mcdaniel/atom#6]

**Comment by adam-mcdaniel** [comment]
LOL, yeah this shell isn't great. [I use Dune as my daily driver shell instead of Atom, it's much more convenient and just as powerful!](https://github.com/adam-mcdaniel/dune)

**Comment by adam-mcdaniel** [comment]
Also, you should be able to type either the backtick *or* the apostrophe if you want to use this on your keyboard. If your keyboard doesn't have the apostrophe I have no idea what to do
